"""empty message

Revision ID: 443dd902c090
Revises: d3dd767b1b98
Create Date: 2023-02-23 10:24:36.151740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443dd902c090'
down_revision = 'd3dd767b1b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
