"""empty message

Revision ID: 8ade97bd574a
Revises: 781ebb8a7f48
Create Date: 2023-02-27 19:48:06.058420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ade97bd574a'
down_revision = '781ebb8a7f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.drop_column('post_pic')

    # ### end Alembic commands ###
