"""empty message

Revision ID: bce66eaa6e5f
Revises: fffdc1c3c079
Create Date: 2023-02-27 19:57:06.406354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce66eaa6e5f'
down_revision = 'fffdc1c3c079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.drop_column('Avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Avatar', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
