"""empty message

Revision ID: d3dd767b1b98
Revises: 3901a5c907f8
Create Date: 2023-02-23 10:19:41.341415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3dd767b1b98'
down_revision = '3901a5c907f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
