"""empty message

Revision ID: fffdc1c3c079
Revises: 8ade97bd574a
Create Date: 2023-02-27 19:54:42.235247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffdc1c3c079'
down_revision = '8ade97bd574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Avatar', sa.String(), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('Avatar')

    # ### end Alembic commands ###
